######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 15 21:42:28 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PicSeeOne.h PicSeeOneregex.h
SOURCES += PicSeeOne.cpp PicSeeOnemain.cpp PicSeeOneregex.cpp
